workflows:
  alpine_printpack_ios:
    name: Alpine Printpack iOS Build
    max_build_duration: 90
    environment:
      flutter: stable
      xcode: latest

    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.alpine.printpack.costing   # CHANGE THIS
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        api_key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        team_id: $APPLE_TEAM_ID

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - yashrochlani7@gmail.com
